### PR TITLE
Added support for Ethernet on ESP32 with W5500.

### PR DESCRIPTION
**Pull request by jonoxer**
Works, but some things still need to be checked / improved:
 * Getting the MAC address from ESP32 chip ID sets the last 2 bytes as 0x00 0x00. Needs investigation.
 * Currently does the W5500 chip reset process no matter what board it's running on. This should be conditional.

### CODE REVIEW

**Comment by sumnerboy12** [comment]
Found this article about ESP32 chip ID... https://forum.arduino.cc/t/esp8266-style-chipid-for-esp32/589349

Sounds like it is in reverse order so you need to take the last 6 bytes and reverse them?

**Comment by sumnerboy12** [comment]
Not sure I follow the W5500 reset comment - are you saying `resetWiznetChip()` just needs to be inside a `#ifdef ARDUINO_ARCH_ESP32`?

**Comment by sumnerboy12** [comment]
> Found this article about ESP32 chip ID... https://forum.arduino.cc/t/esp8266-style-chipid-for-esp32/589349
> 
> Sounds like it is in reverse order so you need to take the last 6 bytes and reverse them?

Another forum post... https://www.reddit.com/r/esp32/comments/fan3rj/unique_id/

**Comment by jonoxer** [comment]
Thanks for the info about the Chip ID being backwards! I didn't know that. I'll experiment with that.

I hadn't thought about putting resetWiznetChip() inside an ifdef. It'll probably be required if we have other boards that use a W5500, such as an updated EtherMega in the future.

**Comment by jonoxer** [comment]
I now have a version that works much better and takes into account the Ethernet MAC offset from the ESP32 base MAC. I need to prettify it a bit, then I'll do a new PR later today.

**Comment by sumnerboy12** [comment]
Nice one! Once merged i will cherry pick this stuff into the UIO and USC
firmware.

**Comment by jonoxer** [comment]
There's a new commit appended to the merge now.

Because the ESP32 actually has 4 MAC addresses assigned, I've changed some variable names to make it clear that what we're using is the Ethernet MAC address instead of the base MAC address. The base MAC address is used for the WiFi interface, and if the ESP32 has both WiFi and Ethernet active at the same time they must have different MACs.

With this PR the MQTT client ID is derived from the Ethernet MAC, because that's the only connection method we currently support. In future when WiFi is added, we should probably generate the MQTT client ID based on which connection is active to avoid any confusion. It's nice when the client ID that shows up on the MQTT broker matches the MAC of the device because that helps with things like finding the client IP in ARP tables.

**Comment by jonoxer** [comment]
I've now gone far beyond these changes, with a new version that makes Ethernet support optional so that it can be turned off with a flag in the config file. With Ethernet turned off, pressing buttons causes updates in the serial console and on the LCD as normal, but it doesn't attempt to connect to MQTT so it's possible to do testing and development without having an Ethernet connection.

I've also added WiFi support, and set up independent MQTT clients so that it can connect to both Ethernet and WiFi simultaneously, with different client IDs and topics for each connection.

**Comment by sumnerboy12** [comment]
Sounds great - will these latest changes be in a new PR or added to this one?

**Comment by jonoxer** [comment]
Those changes are much more invasive so I want to do them separately. I probably haven't done it in the neatest way so I want to get some feedback on it before merging it into main and doing a PR.

**Comment by sumnerboy12** [comment]
Ok - so are these changes ready for a final review/merge?

**Comment by jonoxer** [comment]
Yes, if this PR is acceptable then it can be merged. Then I'll create a new PR for the bigger changes.

**Comment by sumnerboy12** [comment]
The only outstanding question I have is the conditional Wiznet reset you mentioned earlier. Is this needed?

**Comment by jonoxer** [comment]
It does seem to be required for the W5500. It would make sense to perhaps be able to set the pin allocation for reset to be "null", and then the function would be called but not do anything. I can make that change if you like.

**Comment by jonoxer** [comment]
That's a much simpler method. I'll do that :-)

**Review by sumnerboy12 — APPROVED** [review]
Looks good to me.

**Pull request merged**
